// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Switchgear_TimeTracker.Models;

[Table("tbl_Backplates")]
[Index("PanelId", "Section", "Position", Name = "unique_backplate_info", IsUnique = true)]
public partial class TblBackplate
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("PanelID")]
    public int? PanelId { get; set; }

    [StringLength(1)]
    public string Section { get; set; }

    public short? Position { get; set; }

    [ForeignKey("PanelId")]
    [InverseProperty("TblBackplates")]
    public virtual TblProjectPanelInfo Panel { get; set; }

    [InverseProperty("Backplate")]
    public virtual ICollection<TblLaborTimeStamp> TblLaborTimeStamps { get; set; } = new List<TblLaborTimeStamp>();
}