// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Switchgear_TimeTracker.Models;

[Table("tbl_labor_time_stamps")]
public partial class TblLaborTimeStamp
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    [Column("TaskID")]
    public int? TaskId { get; set; }

    [Column("ClockIN", TypeName = "datetime")]
    public DateTime ClockIn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ClockOut { get; set; }

    [Column("BackplateID")]
    public int? BackplateId { get; set; }

    public int? DowntimeReasonID { get; set; }

    [ForeignKey("BackplateId")]
    [InverseProperty("TblLaborTimeStamps")]
    public virtual TblBackplate Backplate { get; set; }

    [ForeignKey("DowntimeReasonID")]
    [InverseProperty("TblLaborTimeStamps")]
    public virtual TblDowntimeReason DowntimeReason { get; set; }

    [ForeignKey("TaskId")]
    [InverseProperty("TblLaborTimeStamps")]
    public virtual TblTemplatePlanningPanelInfo Task { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("TblLaborTimeStamps")]
    public virtual TblEmployee User { get; set; }
}