// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Switchgear_TimeTracker.Models;

[Table("tbl_template_planning_area")]
public partial class TblTemplatePlanningArea
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [InverseProperty("Area")]
    public virtual ICollection<TblTemplatePlanningPanelInfo> TblTemplatePlanningPanelInfos { get; set; } = new List<TblTemplatePlanningPanelInfo>();

    [InverseProperty("Area")]
    public virtual ICollection<TblTemplatePlanningTime> TblTemplatePlanningTimes { get; set; } = new List<TblTemplatePlanningTime>();
}